### PR TITLE
s3: fix bug syncing objects with + signs from s3 buckets

### PR DESCRIPTION
**Pull request by facetoe**
S3 requires + signs to be urlencoded. Catch the error thrown in this
case (403) and detect if we are talking to an S3 bucket. If so, attempt
to download the file again with the + sign escaped.

### CODE REVIEW

**Comment by rikonen** [comment]
Is there some HTTP server that would fail if + was properly percent encoded from get go? It is reserved character per the RFC so sending it unencoded under any circumstance sounds like a bug.

**Comment by facetoe** [comment]
Yea I'm kindof surprised requests doesn't encode it by default. The Fedora upstream repositories handle the percent encoded + sign fine so I will change this to always send it encoded.

**Comment by facetoe** [comment]
Hmm apparently the + sign should be treated literally if it is part of the path component - https://stackoverflow.com/questions/1005676/does-a-in-a-url-scheme-host-path-represent-a-space.

**Review by lionbee — APPROVED** [review]
LGTM

**Pull request merged**
